name: Create Weekly Issue

on:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get current date
        id: date
        run: echo "date=$(date +'%y.%m.%d')" >> $GITHUB_ENV

      - name: Create GitHub Issue
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: "[1 Minute Share] ${{ env.date }}"
          body: |
            이번 주 진행 상황을 공유합니다.
          labels: "1 Min Share"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
