name: Create Weekly Issue

on:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

permissions:
  issues: write 

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get current date
        id: date
        run: echo "date=$(date +'%y.%m.%d')" >> $GITHUB_ENV

      - name: Create GitHub Issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueTitle = `[1 Minute Share] ${{ env.date }}`
            const issueBody = "이번 주 진행 상황을 공유합니다."
            const labels = ["1 Min Share"]
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: labels
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
